image: maven:3.8.5-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots"

cache:
  paths:
#  - target/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS --activate-profiles default compile
  only:
  - develop

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS --activate-profiles default test
  only:
  - develop

deploy:
  stage: deploy
  script:
  - mvn $MAVEN_CLI_OPTS --activate-profiles default -s .mvn-settings.xml deploy
  before_script:
  - update-ca-certificates
  only:
  - develop

release:
  stage: deploy
  script:
  - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$CI_COMMIT_TAG
  - mvn $MAVEN_CLI_OPTS --activate-profiles production -s .mvn-settings.xml deploy
  before_script:
  - update-ca-certificates
  rules:
    - if: '$CI_COMMIT_TAG != null'
